
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 21 17:40:41 ECT 2022
//----------------------------------------------------

package syntactic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 7;
  public static final int SIGNO_SLASH = 4;
  public static final int SIGNO_MENOR = 2;
  public static final int ERROR = 8;
  public static final int EOF = 0;
  public static final int NUMERO = 5;
  public static final int SIGNO_MAYOR = 3;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 6;
}

